services:

  terraform-mcp-server:
    image: hashicorp/terraform-mcp-server:0.3.3
    container_name: terraform-mcp-server
    ports:
      - "8080:8080"
    environment:
      - 'TRANSPORT_MODE=streamable-http'
      - 'TRANSPORT_HOST=0.0.0.0'
      - 'TFE_TOKEN=${TFE_TOKEN}'

  ollama:
    build:
      context: Dockerfiles
      dockerfile: Dockerfile.ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    environment:
      - 'OLLAMA_CONTEXT_LENGTH=131072'

  langflow:
    build:
      context: Dockerfiles
      dockerfile: Dockerfile.langflow
    container_name: langflow
    ports:
      - "7860:7860"
    environment:
      - 'LANGFLOW_HOST=0.0.0.0'
      - 'LANGFLOW_OPEN_BROWSER=false'
      - 'LANGFLOW_WORKER_TIMEOUT=1800'
    volumes:
      - langflow_data:/app/langflow
    depends_on:
      - ollama
    restart: unless-stopped

  opensearch:
    build:
      context: Dockerfiles
      dockerfile: Dockerfile.opensearch
    container_name: opensearch
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - action.auto_create_index=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    restart: unless-stopped

volumes:
  ollama_data: {}
  langflow_data: {}
  opensearch_data: {}