apiVersion: v1
kind: ServiceAccount
metadata:
  name: opensearch
  annotations:
    # This annotation links the Kubernetes service account to the AWS IAM role
    eks.amazonaws.com/role-arn: "arn:aws:iam::224382219437:role/infra-agent-dev-opensearch-irsa"

# Made with Bob
