## TODO: Figure out why it locks the file system on startup
securityContext:
  readOnlyRootFilesystem: false

langflow:
  backend:
    image:
      repository: 224382219437.dkr.ecr.us-east-1.amazonaws.com/infra-agent-langflow
      tag: 6d41795303b633cc69309ec5c012aa4dfbdb195c
    sqlite:
      volume:
        size: "20Gi"
        storageClass:
          provisioner: ebs.csi.eks.amazonaws.com
    autoLogin: false
    superuser: admin
    newUserIsActive: true
    resources:
      requests:
        cpu: 2
        memory: 6Gi
    env:
      - name: LANGFLOW_WORKER_TIMEOUT
        value: "3000"

  frontend:
    resources:
      requests:
        cpu: 2
        memory: 6Gi